#!/usr/bin/env bash
# book-to-deep-reads · GitHub Pages deploy script
# Generated by the skill. Adjust the variables below before running.
#
# Run from inside the publish-safe directory (NEVER from personal/).
# Usage: cd ~/deep-reads/<slug>  &&  bash deploy.sh
#        cd ~/deep-reads/<slug>/public  &&  bash ../deploy.sh
#
# WARNING: this performs an irreversible public publish. Read the PII checks.

set -euo pipefail

# ─── EDIT THESE ──────────────────────────────────────────────────────────────
REPO_NAME="die-with-zero-deep-read"          # e.g. "psychology-of-money" or "die-with-zero"
DESCRIPTION="Self-study deep-read tutorial for Die With Zero by Bill Perkins"      # short repo description
COHORT_KEYWORDS=()  # bash array of identity-marker strings derived
                    # at runtime from the --cohort argument.
                    # Leave as () if no --cohort was used.
# ─────────────────────────────────────────────────────────────────────────────

cwd="$(pwd)"

# ─── PII FIREWALL ────────────────────────────────────────────────────────────
# Rule 1: never publish from inside personal/
case "$cwd" in
  */personal|*/personal/*)
    echo "❌ ABORT: this directory is 'personal/' (contains cohort-personalized content)."
    echo "   Publishing it to a public repo would expose personally identifiable info."
    echo "   To publish the sanitized version, cd to ../public and re-run."
    exit 1
    ;;
esac

# Rule 2: never publish a working tree that contains a personal/ subdir
if [ -d "./personal" ]; then
  echo "❌ ABORT: 'personal/' subdirectory present in working tree."
  echo "   The deploy would push personal/ to a public repo."
  echo "   Either cd into ./public, or remove ./personal first."
  exit 1
fi

# Rule 3: grep cohort keywords against all HTML to be pushed
if [ ${#COHORT_KEYWORDS[@]} -gt 0 ]; then
  echo "🔍 Scanning for cohort keywords (PII guard)..."
  hits=0
  for kw in "${COHORT_KEYWORDS[@]}"; do
    if grep -rl --include="*.html" -- "$kw" . 2>/dev/null | head -1 | grep -q .; then
      echo "   ⚠ Found '$kw' in HTML files:"
      grep -rln --include="*.html" -- "$kw" . | sed 's/^/      /'
      hits=$((hits + 1))
    fi
  done
  if [ $hits -gt 0 ]; then
    echo "❌ ABORT: $hits cohort keyword(s) found in HTML. Not safe to publish."
    echo "   Either use the 'public/' (PII-sanitized) version, or manually scrub these files."
    exit 1
  fi
  echo "   ✓ No cohort keywords found."
fi

# ─── PREP ────────────────────────────────────────────────────────────────────
# Ensure noindex meta is present in every HTML (idempotent insert after <meta charset>)
echo "🔧 Ensuring noindex meta on all HTML..."
for f in *.html; do
  [ -f "$f" ] || continue
  if ! grep -q 'name="robots"' "$f"; then
    # sed -i '' is BSD/macOS syntax
    sed -i '' 's|<meta charset="utf-8">|<meta charset="utf-8">\
  <meta name="robots" content="noindex, nofollow, noarchive">|' "$f"
    echo "   + added to $f"
  fi
done

# robots.txt (belt + suspenders)
if [ ! -f robots.txt ]; then
  cat > robots.txt <<'EOF'
User-agent: *
Disallow: /
EOF
  echo "   + created robots.txt"
fi

# .nojekyll so GitHub Pages serves underscore-prefixed dirs (e.g., _research/)
touch .nojekyll

# ─── GH AUTH CHECK ───────────────────────────────────────────────────────────
if ! command -v gh >/dev/null 2>&1; then
  echo "❌ gh CLI not found. Install: brew install gh"
  exit 1
fi
if ! gh auth status >/dev/null 2>&1; then
  echo "❌ gh not authenticated. Run: gh auth login"
  exit 1
fi

GH_USER="$(gh api user --jq .login)"
PAGES_URL="https://${GH_USER}.github.io/${REPO_NAME}/"

# ─── GIT INIT + PUSH ─────────────────────────────────────────────────────────
if [ ! -d .git ]; then
  git init -b main >/dev/null
  echo "🔧 git initialized."
fi

git add .
if ! git diff --cached --quiet; then
  git commit -m "Initial: ${DESCRIPTION}" >/dev/null
  echo "🔧 committed."
fi

# Create repo and push (public, with description)
if ! gh repo view "${GH_USER}/${REPO_NAME}" >/dev/null 2>&1; then
  gh repo create "${REPO_NAME}" --public --source . --push --description "${DESCRIPTION}"
  echo "🔧 created and pushed to ${GH_USER}/${REPO_NAME}"
else
  git push -u origin main 2>/dev/null || true
  echo "🔧 repo exists; pushed."
fi

# ─── ENABLE PAGES ────────────────────────────────────────────────────────────
gh api -X POST "repos/${GH_USER}/${REPO_NAME}/pages" \
  -f 'source[branch]=main' \
  -f 'source[path]=/' >/dev/null 2>&1 || true

# ─── DONE ────────────────────────────────────────────────────────────────────
echo ""
echo "✅ Deployed."
echo "   Repo:  https://github.com/${GH_USER}/${REPO_NAME}"
echo "   Pages: ${PAGES_URL}  (allow 1–2 min for first build)"
echo ""
echo "ℹ Site is set to noindex + Disallow: / — search engines won't crawl it."
echo "   Anyone with the URL can still view it. Don't broadcast the link if it's sensitive."
